### ISSUE TITLE
Error reported using lua53

### ISSUE THREAD

**Issue by bigboom945** [ogwayTheMagnificent/KungFuscator#1]
I used it to obfuscate my lua script and then executed the obfuscated lua script with lua53 and got an error, here is the error: C:\Users\86186\Desktop\KungFuscator-main>lua output.lua
lua: output.lua:1: attempt to call a nil value (local '__OOGWAY__V')
stack traceback:
        output.lua:1: in function <output.lua:1>
        (...tail calls...)
        [C]: in ?

**Comment by 023948799e213e21b53eb83785356208** [comment]
It only supports lua 5.1

**Comment by ogwayTheMagnificent** [comment]
Please read prometheu's documentation, It only supports Lua 5.1 and LuaU for now
