### ISSUE TITLE
Aye why doesnt it support luaU

### ISSUE THREAD

**Issue by 023948799e213e21b53eb83785356208** [ogwayTheMagnificent/KungFuscator#2]
add something to make it support

**Comment by ogwayTheMagnificent** [comment]
It does, or maybe use original prometheus and read its documentations.

**Comment by 023948799e213e21b53eb83785356208** [comment]
> It does, or maybe use original prometheus and read its documentations.

No its from the src/main.lua or kungfuscator.lua thats making the problem.
